/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mtricks_xe_Cocos2dxHelper_Cocos2dxHelperListener */

#ifndef _Included_com_mtricks_xe_Cocos2dxHelper_Cocos2dxHelperListener
#define _Included_com_mtricks_xe_Cocos2dxHelper_Cocos2dxHelperListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
