#ifndef WIN32
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mtricks_xe_XRenderer */

#ifndef _Included_com_mtricks_xe_XRenderer
#define _Included_com_mtricks_xe_XRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mtricks_xe_XRenderer
 * Method:    nativeCreateMain
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_mtricks_xe_XRenderer_nativeInit
	(JNIEnv *, jobject, jint width, jint height);
	
/*
 * Class:     com_mtricks_xe_XRenderer
 * Method:    nativeFrameMove
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_mtricks_xe_XRenderer_nativeFrameMove
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_mtricks_xe_XRenderer
 * Method:    nativeDraw
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mtricks_xe_XRenderer_nativeDraw
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_mtricks_xe_XRenderer_nativeTouchesDown
  (JNIEnv *, jobject, jint id, jfloat mx, jfloat my);

JNIEXPORT void JNICALL Java_com_mtricks_xe_XRenderer_nativeTouchesUp
  (JNIEnv *, jobject, jint id, jfloat mx, jfloat my);

JNIEXPORT void JNICALL Java_com_mtricks_xe_XRenderer_nativeTouchesMove
  (JNIEnv *, jobject, jint id, jfloat mx, jfloat my);

JNIEXPORT void JNICALL Java_com_mtricks_xe_XRenderer_nativeTouchesZoom
(JNIEnv *, jobject, jint id, jfloat mx, jfloat my, jfloat scale);

JNIEXPORT void JNICALL Java_com_mtricks_xe_XRenderer_nativeOnPause
	(JNIEnv *, jobject);
JNIEXPORT void JNICALL Java_com_mtricks_xe_XRenderer_nativeOnResume
	(JNIEnv *, jobject);
JNIEXPORT void JNICALL Java_com_mtricks_xe_XRenderer_nativeOnDestroy
	(JNIEnv *, jobject);
JNIEXPORT void JNICALL Java_com_mtricks_xe_XRenderer_nativeOnKeyEvent
	(JNIEnv *env, jobject, jint keyCode, jint keyAction );
JNIEXPORT void JNICALL Java_com_mtricks_xe_XRenderer_nativeOnPurchaseFinishedConsume
	(JNIEnv *, jobject, jstring strJson, jstring stridProduct, jstring jstrToken, jstring jstrPrice, jstring jstrOrderId, jlong jlongTime );
JNIEXPORT void JNICALL Java_com_mtricks_xe_XRenderer_nativeOnPurchaseError
	(JNIEnv *env, jobject, jstring jstrErr );
JNIEXPORT void JNICALL Java_com_mtricks_xe_XRenderer_nativeOnResultAuthenIni3
	(JNIEnv *env, jobject, jstring jstrUserId, jstring jstrUserName, jboolean jbByFacebookLogin );
JNIEXPORT void JNICALL 
	Java_com_mtricks_xe_XRenderer_nativeOnResultAuthenFacebook
	(JNIEnv *env, jobject, jstring jstrUserId, jstring jstrUserName );
JNIEXPORT void JNICALL 
	Java_com_mtricks_xe_XRenderer_nativeOnRecvProfileImage
	(JNIEnv *env, jobject, jstring jstrFbUserId, jintArray ary, jint w, jint h, jint bpp );
JNIEXPORT void JNICALL 
	Java_com_mtricks_xe_XRenderer_nativeOnInitGoogleIAPAsync(JNIEnv *env, jobject);
JNIEXPORT void JNICALL
	Java_com_mtricks_xe_XRenderer_nativeOnDetectedUnConsumedItem( JNIEnv *env, jobject
																															, jstring jstrJson
																															, jstring jstrSignature );
JNIEXPORT void JNICALL
Java_com_mtricks_xe_XRenderer_nativeOncbOnClickedBuyItem( JNIEnv *env, jobject
																												, jboolean _bOk
																												, jstring jstrJsonReceipt
																												, jstring jstrSignature
																												, jstring jstrIdsProduct );
JNIEXPORT void JNICALL
Java_com_mtricks_xe_XRenderer_nativeOnFinishedConsumeItem( JNIEnv *env, jobject
																												, jboolean _bOk
																												, jstring jstrSku);

// JNIEXPORT void JNICALL 
// Java_com_mtricks_xe_XRenderer_nativeOnRecvProfileImage
// (JNIEnv *env, jobject, jint jimage[], jint length );

#ifdef __cplusplus
}
#endif
#endif
#endif // not win32