#pragma once
// 게임서버<->클라이언트간 패킷
#include "VerPacket.h"

// enum이므로 중간에 끼워넣어도 됨
enum xtPacket {
	xPK_NONE=0,
	xPK_SAMPLE,

	xPK_ACCOUNT = 10000,
	xPK_ACCOUNT_NEW,
	xPK_ACCOUNT_REGISTER,
	xPK_ACCOUNT_INFO_SAVE,
	xPK_ACCOUNT_LOGIN_FROM_ID,
	xPK_ACCOUNT_LOGIN_FROM_UUID,	
	xPK_ACCOUNT_SESSION_ID,
	xPK_ACCOUNT_SESSION_UUID,
	xPK_ACCOUNT_LOGIN,
	xPK_DIFF_PACKET_VER,
	xPK_ACCOUNT_NOT_EXIST,
	xPK_ACCOUNT_FAILED_LOGIN,
	xPK_SEND_ACCOUNT_ID,
	xPK_ACCOUNT_LOGOUT,
	xPK_ACCOUNT_RECONNECT_TRY,		//중복 접속 이니까 다시 접속 시도 하라고 알림.
	xPK_ACCOUNT_RECONNECT_UUID,		//서버 요청으로 클라이언트가 UUID 로 재접속 시도 sessionkey 필요
	xPK_ACCOUNT_RECONNECT_ID,			//서버 요청으로 클라이언트가 ID 로 재접속 시도 sessionkey 필요
	xPK_ACCOUNT_DUPLICATE_LOGOUT,	//중복 접속 이니까 접속을 종료 하라고 알림.

	xPK_LOBBY =  xPK_ACCOUNT + 1000,
	xPK_LOBBY_BUY_CASHITEM_BY_IAP,
	// cheat
	xPK_CHEAT,	

	xPK_GAME = xPK_LOBBY + 1000,	
	//pve	
	xPK_GAME_SAMPLE,

	//pvp
	xPK_GAME_PVP_SEND_CHAT,
	xPK_GAME_PVP_REQUEST_USERINFO,
	xPK_GAME_PVP_SEND_USERINFO,
	xPK_GAME_PVP_START_GAME,
	xPK_GAME_PVP_SEND_PING,
	xPK_GAME_PVP_RETURN_PING,
	xPK_GAME_PVP_RESET_TIMER,
	xPK_GAME_PVP_LOAD_FINISH,
	xPK_GAME_PVP_USE_SOLDIER,
	xPK_GAME_PVP_USE_UNIT,
	xPK_GAME_PVP_USE_SKILL,
	xPK_GAME_PVP_NEXT_FRAME,
	xPK_GAME_PVP_SYNC_DEBUG,
	xPK_GAME_PVP_READY_USER,
	xPK_GAME_PVP_CANCEL_READY_USER,
	xPK_GAME_PVP_READY_EXIT,

	xPK_MAX,

	// 여기서부터는 패킷아니고 타임아웃용임
	xTIMEOUT = xPK_GAME + 1000,	// 서버로부터 접속이 끊어지면 발생하는 타임아웃
	xTIMEOUT_BUY_IAP,
};
